---
- name: Set a colored bash prompt.
  template:
    src: ./templates/bash.bashrc
    dest: /etc/bash.bashrc
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  become: yes
  become_method: sudo
...