---
all:
  hosts:
    orange:
      ansible_host: rpicluster_orange
      ansible_port: 65401
      ansible_ssh_private_key_file: ~/.ssh/rpicluster_key
      ansible_user: pirate
    blue:
      ansible_host: rpicluster_blue
      ansible_port: 65402
      ansible_ssh_private_key_file: ~/.ssh/rpicluster_key
      ansible_user: pirate
    black:
      ansible_host: rpicluster_black
      ansible_port: 65403
      ansible_ssh_private_key_file: ~/.ssh/rpicluster_key
      ansible_user: pirate      
    purple:
      ansible_host: rpicluster_purple
      ansible_port: 65404
      ansible_ssh_private_key_file: ~/.ssh/rpicluster_key
      ansible_user: pirate      
    red:
      ansible_host: rpicluster_red
      ansible_port: 65405
      ansible_ssh_private_key_file: ~/.ssh/rpicluster_key
      ansible_user: pirate      
    yellow:
      ansible_host: rpicluster_yellow
      ansible_port: 65406
      ansible_ssh_private_key_file: ~/.ssh/rpicluster_key
      ansible_user: pirate      
    white:
      ansible_host: rpicluster_white
      ansible_port: 65407
      ansible_ssh_private_key_file: ~/.ssh/rpicluster_key
      ansible_user: pirate      
    green:
      ansible_host: rpicluster_green
      ansible_port: 65408
      ansible_ssh_private_key_file: ~/.ssh/rpicluster_key
      ansible_user: pirate      
  children:
    left:
      hosts:
        red:
        yellow:
        white:
        green:
    right:
      hosts:
        orange:
        blue:
        black:
        purple:
    group_a:
      hosts:
        red:
        yellow:
    group_b:
      hosts:
        white:
        green:
    group_c:
      hosts:
        orange:
        blue:
    group_d:
      hosts:
        black:
        purple:
...